export function saveStoryPoints(filename: string, pts: number): void;
export function saveTitle(filename: string, docType: string): void;
export function cancelTitleEdit(): void;
export function updateDocSprint(filename: string, sprint: string): void;
export function updateDocStatus(filename: string, status: string): void;
export function updateDocTeam(filename: string, team: string): void;
export function updateDocWorkCategory(filename: string, cat: string): void;
export function showList(): void;
export function confirmDelete(filename: string, docType: string): void;
export function closeDeleteDialog(): void;
export function executeDelete(): void;
export function toggleDropdown(id: string): void;
export function closeDropdown(id: string): void;
export function closeAllDropdowns(): void;
export function toggleHierarchy(): void;
export function toggleOriginal(): void;
export function openDoc(filename: string, docType: string): void;
export function loadHierarchy(filename: string, docType: string): void;
export function addDocComment(filename: string, docType: string): void;
export function startCommentEdit(idx: number): void;
export function cancelCommentEdit(idx: number): void;
export function saveCommentEdit(filename: string, docType: string, idx: number): void;
export function deleteDocComment(filename: string, docType: string, idx: number): void;
export function linkExistingChildren(filename: string, docType: string): void;
export function toggleHierarchyChild(filename: string): void;
