export function toggleItemCollapse(el: HTMLElement): void;
export function collapseAll(): void;
export function expandAll(): void;
export function toggleSwimlane(section: string): void;
export function updatePiVersion(filename: string, docType: string, version: string): void;
export function setTypeFilter(type: string): void;
export function setStatusFilter(status: string): void;
export function setTeamFilter(team: string): void;
export function setWorkCatFilter(cat: string): void;
export function applyFilters(docs: unknown): void;
export declare const applyFiltersDebounced: (docs: unknown) => void;
export function handleItemClick(e: MouseEvent, filename: string, docType: string): void;
export function handleItemContextMenu(e: MouseEvent, filename: string, docType: string): void;
export function showContextMenu(e: MouseEvent): void;
export function closeContextMenu(): void;
export function contextMoveToPI(section: string): void;
export function contextDeleteSelected(): void;
export function contextAssignField(field: string, value: string): void;
export function closeBulkAssignDialog(): void;
