export function openRoadmapView(): void;
export function closeRoadmapView(): void;
export function refreshRoadmapView(): void;
export function toggleRoadmapPi(pi: string): void;
export function toggleRoadmapPanel(panel: string): void;
export function filterRoadmapEpics(query: string): void;
export function focusEpic(filename: string): void;
export function pushSprintsToJira(): void;
export function closeSprintPushModal(): void;
export function toggleSprintPushFilter(filter: string): void;
export function sprintPushSelectAll(): void;
export function sprintPushToggleAllSprints(): void;
export function startSprintPushPreview(): void;
export function confirmSprintPush(): void;
export function _sprintPushUpdateCount(): void;
export function pullFromJiraSprints(): void;
export function closePullSprintModal(): void;
export function pullSprintToggleAll(checked: boolean): void;
export function startPullSprintPreview(): void;
export function pullSprintSelectAllItems(checked: boolean): void;
export function _pullSprintUpdateCount(): void;
export function confirmPullSprint(): void;
export function addDepLink(filename: string, type: string): void;
export function addParallelLink(filename: string): void;
export function removeDepLink(filename: string, type: string, targetFilename: string): void;
export function closeDepModal(): void;
export function closeSplitModal(): void;
export function executeSplit(): void;
export function handleEpicContextMenu(e: MouseEvent, filename: string): void;
export function handleStoryContextMenu(e: MouseEvent, filename: string): void;
export function rmCtxOpenEpic(filename: string): void;
export function rmCtxMoveEpic(filename: string, targetPi: string): void;
export function rmCtxMoveStory(filename: string, targetEpic: string): void;
export function rmCtxSetSprint(filename: string, sprint: string): void;
